import "./components/button";
import "./components/hands";
import "./components/text";
import "./pages/login";
import "./pages/home";
import "./pages/game-room";
import "./pages/start-game";
import "./pages/countdown";
import "./pages/preview";
import "./pages/result";
import "./router";
import { state } from "./state";
state.init();
